#!/bin/sh

# pkgs we need for our kiosk
chroot $1 apt install -y cage chromium python-is-python3 python3-pip triggerhappy

SERVER_DIR="home/$IGconf_device_user1/server"

# Copy our server and give the kiosk ownership
cp -r ../flowy-image-server "$1/$SERVER_DIR"

# Install python packages
cp ../pyreqs.txt "$1/home/$IGconf_device_user1/pyreqs.txt"
chroot $1 /usr/bin/python -m pip install --break-system-packages -r /home/$IGconf_device_user1/pyreqs.txt

# We'll run chromium like this
KIOSK_APP="/usr/bin/chromium-browser http://localhost:8080/docs --kiosk --noerrdialogs --disable-infobars --no-first-run --ozone-platform=wayland --enable-features=OverlayScrollbar --start-maximized"

# Write out our systemd kiosk service
cat ../services/kiosk.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
   -e "s|<KIOSK_APP>|$KIOSK_APP|g" \
   > $1/etc/systemd/system/kiosk.service

# Write out our systemd backend service (python)
cat ../services/kioskserver.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
   -e "s|<SERVER_DIR>|/$SERVER_DIR|g" \
   > $1/etc/systemd/system/kioskserver.service

# Enable the kiosk service so it starts automatically

$BDEBSTRAP_HOOKS/enable-units "$1" kioskserver
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk

cat > "$1/usr/local/bin/emergency-kiosk-disable.sh" << 'EOF'
#!/bin/bash
systemctl stop kiosk.service && systemctl disable kiosk.service && pkill -f chromium
EOF
chmod 755 "$1/usr/local/bin/emergency-kiosk-disable.sh"
echo "KEY_LEFTCTRL+KEY_LEFTSHIFT+KEY_K 1 /usr/local/bin/emergency-kiosk-disable.sh" > "$1/etc/triggerhappy/triggers.d/emergency.conf"
echo "$IGconf_device_user1 ALL=(root) NOPASSWD: /usr/local/bin/emergency-kiosk-disable.sh" > "$1/etc/sudoers.d/emergency"
chmod 440 "$1/etc/sudoers.d/emergency"