#!/bin/sh

# pkgs we need for our kiosk
chroot $1 apt install -y cage chromium python-is-python3 python3-pip python3.11-venv triggerhappy build-essential python3-dev plymouth plymouth-themes

# Create flowy directory
mkdir -p $1/flowy
chroot $1 chown -R $IGconf_device_user1:$IGconf_device_user1 /flowy

SERVER_DIR="/flowy/server"

# Copy our server and python requirements list
cp -r ../flowy-server "$1$SERVER_DIR"
cp ../pyreqs.txt "$1$SERVER_DIR/pyreqs.txt"

chroot $1 /usr/bin/python -m venv $SERVER_DIR/.venv
PYTHON_DIR=$SERVER_DIR/.venv/bin

chroot $1 $PYTHON_DIR/pip install -r $SERVER_DIR/pyreqs.txt

# Set up chromium arguments
KIOSK_APP="/usr/bin/chromium-browser http://localhost:8080/ --kiosk --noerrdialogs --disable-infobars --no-first-run --ozone-platform=wayland --enable-features=OverlayScrollbar --start-maximized"

SYS_DIR="$1/etc/systemd/system"
for service in kiosk kioskserver wifiserver nfcserver; do
   case $service in
      kiosk)
         sed -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
             -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1|g" \
             -e "s|<KIOSK_APP>|$KIOSK_APP|g" \
            ../services/$service.service.tpl > $SYS_DIR/flowy-$service.service
            ;;
      kioskserver)
         sed -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
             -e "s|<SERVER_DIR>|$SERVER_DIR/wifi-web|g" \
             -e "s|<PYTHON_EXEC>|$PYTHON_DIR/python|g" \
            ../services/$service.service.tpl > $SYS_DIR/flowy-$service.service
            ;;
      wifiserver)
         sed -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
             -e "s|<SERVER_DIR>|$SERVER_DIR/wifi|g" \
             -e "s|<PYTHON_EXEC>|$PYTHON_DIR/python|g" \
            ../services/$service.service.tpl > $SYS_DIR/flowy-$service.service
            ;;
      nfcserver)
         sed -e "s|<KIOSK_USER>|$IGconf_device_user1|g" \
             -e "s|<SERVER_DIR>|$SERVER_DIR/nfc|g" \
             -e "s|<PYTHON_EXEC>|$PYTHON_DIR/python|g" \
            ../services/$service.service.tpl > $SYS_DIR/flowy-$service.service
            ;;
   esac

   # Enable the service
   $BDEBSTRAP_HOOKS/enable-units "$1" flowy-$service
done

# Install flowy protocol handler
cp ../flowy-protocol-handler.sh "$1/usr/local/bin/flowy-protocol-handler.sh"
chmod +x "$1/usr/local/bin/flowy-protocol-handler.sh"

# Install protocol handler desktop file system-wide
mkdir -p "$1/usr/share/applications"
cp ../flowy-protocol.desktop "$1/usr/share/applications/"

# Configure Plymouth splash screen
echo "Configuring Plymouth splash screen..."

# Set default theme to spinner (clean and simple)
chroot $1 plymouth-set-default-theme spinner

# Configure kernel command line for silent boot with Plymouth
CMDLINE_FILE="$1/boot/firmware/cmdline.txt"
if [ -f "$CMDLINE_FILE" ]; then
    # Add Plymouth and quiet boot parameters
    sed -i 's/$/ quiet splash plymouth.ignore-serial-consoles/' "$CMDLINE_FILE"
else
    echo "Warning: cmdline.txt not found, Plymouth may not work properly"
fi

# Update initramfs to include Plymouth
chroot $1 update-initramfs -u