pcm.dmixer {
    type dmix
    ipc_key 2048
    slave {
        pcm "hw:sndrpihifiberry,0"
        rate 44100
        channels 2
        format S16_LE
        period_size 1024
        buffer_size 8192
    }
}
pcm.softvol {
    type softvol
    slave.pcm "dmixer"
    control { name "SoftMaster"; card sndrpihifiberry }
    min_dB -40.0
    max_dB 0.0
}
pcm.!default { type plug; slave.pcm "softvol" }
ctl.!default { type hw; card sndrpihifiberry }
