#!/bin/sh
# Rotate DSI-2 output 270 degrees (corrected display name)
wlr-randr --output DSI-2 --transform 270 &

# Start kiosk app on DSI
gtk-launch flowy-app &

# Optionally start Chromium on HDMI
# chromium --ozone-platform-hint=wayland &
